### ISSUE TITLE
Cannot run predict_landmarks.py

### ISSUE THREAD

**Issue by HideUnderBush** [papulke/face-of-art#59]
Dear author, 

Thanks for sharing your code!

I found some problems when testing the scripts. I first downloaded the datasets as well as the pre-trained models, and then changed the related file paths and executed the script directly `python3 predict_landmarks.py`

However, I first got some complaints about the convention from py2 to py3 such as using print() rather than print at menpofit/clm/algorithm/gd.py:363

And then I got the following messages:
> Traceback (most recent call last):
>   File "predict_landmarks.py", line 58, in <module>
>     reuse=reuse, map_to_input_size=map_landmarks_to_original_image)
>   File "/home/chloe/face-of-art/deep_heatmaps_model_fusion_net.py", line 822, in get_landmark_predictions
>     p_pdm_lms = feature_based_pdm_corr(lms_init=init_lms, models_dir=pdm_models_dir, train_type='basic')
>   File "/home/chloe/face-of-art/pdm_clm_functions.py", line 160, in feature_based_pdm_corr
>     pdm_temp = pickle.load(filehandler, fix_imports=True, encoding="latin1")
> _pickle.UnpicklingError: unpickling stack underflow

I simply changed the encoding way from "latin1" to "bytes" as a solution, however, I am not sure if it is correct or not. 

And then, I got this error:

> Traceback (most recent call last):
>   File "predict_landmarks.py", line 58, in <module>
>     reuse=reuse, map_to_input_size=map_landmarks_to_original_image)
>   File "/home/chloe/face-of-art/deep_heatmaps_model_fusion_net.py", line 822, in get_landmark_predictions
>     p_pdm_lms = feature_based_pdm_corr(lms_init=init_lms, models_dir=pdm_models_dir, train_type='basic')
>   File "/home/chloe/face-of-art/pdm_clm_functions.py", line 165, in feature_based_pdm_corr
>     part_lms_pdm = pdm_correct(lms_init[part_inds], pdm_temp)
>   File "/home/chloe/face-of-art/pdm_clm_functions.py", line 86, in pdm_correct
>     pdm_model.set_target(PointCloud(init_shape))
>   File "/home/chloe/.local/lib/python3.6/site-packages/menpo/base.py", line 229, in set_target
>     self._target_setter_with_verification(new_target)  # trigger the update
>   File "/home/chloe/.local/lib/python3.6/site-packages/menpo/base.py", line 244, in _target_setter_with_verification
>     self._verify_target(new_target)
>   File "/home/chloe/.local/lib/python3.6/site-packages/menpo/base.py", line 266, in _verify_target
>     if self.target is None:
>   File "/home/chloe/face-of-art/menpofit/modelinstance.py", line 114, in target
>     return self._target
> AttributeError: 'OrthoPDM' object has no attribute '_target'

Did I miss any settings? Or what should I do to run through this script?

Thank you for your time!

**Comment by halfjoe** [comment]
@HideUnderBush Hi, thanks for sharing. I've got the same error as yours. Have you found the solution?

**Comment by papulke** [comment]
Hi @HideUnderBush & @halfjoe ,

I'm sorry for the late reply!

The OrthoPDM error is probably due to differences in the menpo library versions. In my project, I use the following version: 0.8.1

The menpofit code is taken from the original ECT implementation (https://github.com/HongwenZhang/ECT-FaceAlignment), which is in python 2.
In my project, this code is used for the landmarks tuning stage.

 Hope this helps!

**Comment by halfjoe** [comment]
@papulke  Thanks for the tips! That helps.

For those who also want to build an environment to run the code, here is a summary (using conda). 

First you should assign the menpo version and install menpofit together when creating the conda environment, like
`conda create -n your_environment_name -c menpo menpo=0.8 menpofit`
Usable version of menpo and menpofit will be installed along with Python2. Then install tensorflow-gpu and not assigning specific version is ok. Then install other packages missed.

You may as well need to downgrade package "dask" to 1.2.0, if something goes wrong with it.

No need to change print function (as you are using Python2) and encoding problem will not happen.

**Comment by SystemErrorWang** [comment]
hello, i tried running this code, though i got no error messages, but it just generates no results, and it seems the for loop ends in the first iteration. Does anyone come across this problem? any suggestion is appreciated

**Comment by halfjoe** [comment]
@SystemErrorWang Hi, have you put the images in the right places? Maybe the for loop ends because the image list to read is empty.

**Comment by SystemErrorWang** [comment]
@halfjoe I failed on mac os, and later tried linux and succeeded, but still have no idea of the reason.

**Comment by justinpinkney** [comment]
I was encountering the issues above too. I managed to get a copy up and running with the pretrained models and have added a Dockerfile in my fork with everything that seems to be required for inference  (haven't tried training yet): https://github.com/justinpinkney/face-of-art/blob/master/Dockerfile

**Comment by DAVID-Hown** [comment]
@halfjoe 
Excuse me, how do you set some file paths in the code? I'm reporting an error during the run, okay?
ssh://julyedu_623899@101.133.217.125:22/usr/share/anaconda3/envs/py37/bin/python -u /students/julyedu_623899/face_of_art/face-of-art/predict_landmarks.py
Traceback (most recent call last):
  File "/students/julyedu_623899/face_of_art/face-of-art/predict_landmarks.py", line 42, in <module>
    bb_dictionary=bb_dictionary, mode='TEST', return_transform=map_landmarks_to_original_image)
  File "/students/julyedu_623899/face_of_art/face-of-art/menpo_functions.py", line 296, in load_menpo_image_list
    out_image_list = mio.import_images(img_set_dir, verbose=verbose, normalize=False)
  File "/students/julyedu_623899/.local/lib/python3.7/site-packages/menpo/io/input/base.py", line 672, in import_images
    importer_kwargs=kwargs,
  File "/students/julyedu_623899/.local/lib/python3.7/site-packages/menpo/io/input/base.py", line 868, in _import_glob_lazy_list
    filepaths = list(glob_with_suffix(pattern, extension_map, sort=(not shuffle)))
  File "/students/julyedu_623899/.local/lib/python3.7/site-packages/menpo/io/input/base.py", line 1110, in glob_with_suffix
    for path in _pathlib_glob_for_pattern(pattern, sort=sort):
  File "/students/julyedu_623899/.local/lib/python3.7/site-packages/menpo/io/input/base.py", line 1072, in _pathlib_glob_for_pattern
    raise ValueError("{} is an invalid glob and " "not a dir".format(pattern))
ValueError: /students/julyedu_623899/AF_dataset2/Fernand_Leger is an invalid glob and not a dir

If possible, could you please leave an email address for me？

**Comment by wd2295** [comment]
@papulke  @halfjoe @SystemErrorWang 
Hello, do u use ubuntu? May i ask the version u use? i tried installing menpo=0.8.1, but failed with an error going like this:

 'UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  **- feature:/linux-64::__glibc==2.31=0
  - python=2.7 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31**
'
It seems that i have to use a lower-version glibc. But my ubuntu (20.04) might get corrupted if i downgrade the glibc version from 2.31 to 2.17.

**Comment by wd2295** [comment]
@papulke @halfjoe @SystemErrorWang #
Hello, do u use ubuntu? May i ask the version u use? i tried installing menpo=0.8.1, but failed with an error going like this:

 'UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  **- feature:/linux-64::__glibc==2.31=0
  - python=2.7 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31**
'
It seems that i have to use a lower-version glibc. But my ubuntu (20.04) might get corrupted if i downgrade the glibc version from 2.31 to 2.17.

**Comment by theidealist2** [comment]
@justinpinkney @papulke @SystemErrorWang @halfjoe @HideUnderBush 
Hi, have you met the error named 
"FileNotFoundError: [Errno 2] No such file or directory: '~/landmark_detection_datasets/Bounding_Boxes/bounding_boxes_afw.mat'"
I can't find same dataset called this name provided by the author. Does it is generated by the coder?
If you have the solution, Please Tell Me! Thank you!

**Comment by kruzel** [comment]
I have the same problem as [wd2295](https://github.com/wd2295),
any solution to this?

**Comment by yaelnewman** [comment]
at that time we were working on ubuntu 12.04

**Comment by isedgar** [comment]
This worked for me on Lubuntu.

conda create --name foa python=2.7 tensorflow=1.15
conda activate foa
conda install -c conda-forge opencv=4.1.0
sudo apt-get install libopencv-*
pip install menpo==0.8.1
pip install menpofit==0.5.0

numpy.__version__: 1.16.6
scipy.__version__: 0.19.1
tensorflow.__version__: 1.15.0
cv2.__version__: 4.1.0
menpo.__version__: 0.8.1
menpofit.__version__: 0.5.0
